# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

defaults: &defaults
  adapter: mysql2
  username: root
  password: ""
  host: localhost

development:
  <<: *defaults
  database: netdiffness_development

test:
  <<: *defaults
  database: netdiffness_test
